// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// loadobj
List loadobj(std::string thefile, std::string basepath);
RcppExport SEXP _readobj_loadobj(SEXP thefileSEXP, SEXP basepathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type thefile(thefileSEXP);
    Rcpp::traits::input_parameter< std::string >::type basepath(basepathSEXP);
    rcpp_result_gen = Rcpp::wrap(loadobj(thefile, basepath));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readobj_loadobj", (DL_FUNC) &_readobj_loadobj, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_readobj(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
