# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadobj <- function(thefile, basepath = "", triangulate = TRUE) {
    .Call('_readobj_loadobj', PACKAGE = 'readobj', thefile, basepath, triangulate)
}

